const fs = require("fs");
const path = require("path");

/**
 * Tiny CommonJS bundler for Obsidian releases.
 *
 * It keeps development files split under src/ while producing the single
 * main.js file Obsidian loads from an installed plugin folder.
 */
const ROOT = __dirname;
const ENTRY = "src/plugin.js";
const OUTFILE = "main.js";
const EXTERNALS = new Set(["obsidian"]);
const COMPLETION_SOUND_TOKEN = "__TASK_DECK_COMPLETION_SOUND__";

const modules = new Map();

function moduleId(filePath) {
  return path.relative(ROOT, filePath).split(path.sep).join("/");
}

function resolveRelative(fromFile, request) {
  let resolved = path.resolve(path.dirname(fromFile), request);
  if (!path.extname(resolved)) resolved += ".js";
  return resolved;
}

function collect(filePath) {
  const id = moduleId(filePath);
  if (modules.has(id)) return id;

  let code = fs.readFileSync(filePath, "utf8");
  if (code.includes(COMPLETION_SOUND_TOKEN)) {
    const sound = fs.readFileSync(path.join(ROOT, "bink.wav")).toString("base64");
    code = code.replace(COMPLETION_SOUND_TOKEN, `data:audio/wav;base64,${sound}`);
  }
  code = code.replace(/require\("([^"]+)"\)/g, (match, request) => {
    if (!request.startsWith(".") || EXTERNALS.has(request)) return match;
    return `__require("${collect(resolveRelative(filePath, request))}")`;
  });

  modules.set(id, code);
  return id;
}

const entryId = collect(path.join(ROOT, ENTRY));
const moduleEntries = Array.from(modules.entries())
  .map(([id, code]) => `  ${JSON.stringify(id)}: function(module, exports, __require) {\n${code}\n  }`)
  .join(",\n");

const output = `// Generated by build.js. Edit src/ files, then run: node build.js
const __modules = {
${moduleEntries}
};

const __cache = {};

function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  const factory = __modules[id];
  if (!factory) throw new Error("Module not found: " + id);

  const module = { exports: {} };
  __cache[id] = module;
  factory(module, module.exports, __require);
  return module.exports;
}

module.exports = __require(${JSON.stringify(entryId)});
`;

fs.writeFileSync(path.join(ROOT, OUTFILE), output);
