const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const ENTRY = "src/plugin.js";
const OUTFILE = "main.js";
const EXTERNALS = new Set(["obsidian"]);

const modules = new Map();

function moduleId(filePath) {
  return path.relative(ROOT, filePath).split(path.sep).join("/");
}

function resolveRelative(fromFile, request) {
  let resolved = path.resolve(path.dirname(fromFile), request);
  if (!path.extname(resolved)) resolved += ".js";
  return resolved;
}

function collect(filePath) {
  const id = moduleId(filePath);
  if (modules.has(id)) return id;

  let code = fs.readFileSync(filePath, "utf8");
  code = code.replace(/require\("([^"]+)"\)/g, (match, request) => {
    if (!request.startsWith(".") || EXTERNALS.has(request)) return match;
    return `__require("${collect(resolveRelative(filePath, request))}")`;
  });

  modules.set(id, code);
  return id;
}

const entryId = collect(path.join(ROOT, ENTRY));
const moduleEntries = Array.from(modules.entries())
  .map(([id, code]) => `  ${JSON.stringify(id)}: function(module, exports, __require) {\n${code}\n  }`)
  .join(",\n");

const output = `// Generated by build.js. Edit src/ files, then run: node build.js
const __modules = {
${moduleEntries}
};

const __cache = {};

function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  const factory = __modules[id];
  if (!factory) throw new Error("Module not found: " + id);

  const module = { exports: {} };
  __cache[id] = module;
  factory(module, module.exports, __require);
  return module.exports;
}

module.exports = __require(${JSON.stringify(entryId)});
`;

fs.writeFileSync(path.join(ROOT, OUTFILE), output);
