const { setIcon } = require("obsidian");

// Shared constants plus small pure helpers for dates, labels, Markdown, and DOM controls.
const VIEW_TYPE = "obsidian-nextcloud-deck-view";
const LEGACY_CARD_FOLDER = "Kanban Cards";
const LEGACY_BOARD_INDEX_SUFFIX = "Task Deck Board.md";
// Kept as-is so pre-existing board index files (written by the upstream Task
// Deck plugin) still get recognised on first load; new indexes emit the same
// marker for zero-migration compatibility.
const BOARD_INDEX_MARKER = "Generated by Task Deck so board cards stay connected in Obsidian graph view.";
const TASK_DECK_ICON = "obsidian-nextcloud-deck";
const TASK_DECK_ICON_SVG = `
  <g fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">
    <rect x="14" y="16" width="20" height="68" rx="6" />
    <rect x="40" y="16" width="20" height="52" rx="6" />
    <rect x="66" y="16" width="20" height="38" rx="6" />
    <path d="M21 31h6" />
    <path d="M47 31h6" />
    <path d="M73 31h6" />
  </g>
`;
const LIST_DRAG_TYPE = "application/x-task-deck-list";
const IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp", "avif", "ico"];
const DEFAULT_LABEL_COLOR = "#2f6fd6";
const LABEL_COLORS = [
  "#1f6f4a", "#8a6f00", "#a64b00", "#8b2a24", "#6f338f",
  "#247b55", "#9a7600", "#b85f00", "#be332b", "#8a3db0",
  "#54c99b", "#e5bd12", "#ffa51a", "#f46b66", "#c878ee",
  "#1b4078", "#1f7082", "#426226", "#67264f", "#5d6369",
  "#2465c7", "#2b7c8e", "#4f7822", "#a33e78", "#73787f",
  "#68a0ee", "#70c1d8", "#96c949", "#dc6ab5", "#a3a6aa",
];
const LIST_COLORS = ["#3b82f6", "#22c55e", "#f59e0b", "#ef4444", "#8b5cf6", "#14b8a6", "#ec4899", "#94a3b8"];

/**
 * Minimal saved-data shape used when the plugin starts with no existing board.
 *
 * Cards are stored in a top-level map and lists keep card ids. This makes
 * moving cards between lists cheap while still letting each card have one
 * Markdown file on disk.
 *
 * The `nextcloud` block holds the config + runtime state for the Nextcloud Deck
 * sync feature. It stays disabled until the user completes login in the
 * settings pane, so the plugin behaves as a pure local kanban until then.
 */
const DEFAULT_NEXTCLOUD = {
  enabled: false,
  serverUrl: "",
  username: "",
  // AES-GCM(base64) ciphertext of the App Password. Never stored in plaintext.
  appPasswordCipher: "",
  // localBoardId -> remoteBoardId; populated after the first "bind" flow.
  boardBindings: {},
  lastSyncAt: 0,
  syncIntervalMs: 60000,
  // prompt | local | remote | newer-wins — see docs/plan §5.
  conflictPolicy: "prompt",
  // Attachments are Phase 2 territory; the toggle is here so the data schema
  // is stable now and settings can flip it once implemented.
  attachmentsEnabled: false,
  // Cards deleted locally that still need their remote counterpart torn down
  // on the next push. Shape: [{ remoteId, boardRemoteId, stackRemoteId, at }].
  pendingDeletions: [],
  // Attachments deleted locally that still need to be removed from Nextcloud.
  // Shape: [{ attachmentRemoteId, cardRemoteId, stackRemoteId, boardRemoteId, at }].
  pendingAttachmentDeletions: [],
};

const DEFAULT_DATA = {
  version: 1,
  activeBoardId: "",
  completionSound: true,
  compactLabels: false,
  layoutMigrated: false,
  // When true, plugin logs verbose diagnostics (writeCardFile paths, sync
  // requests, mapper decisions) to both the sync log and the developer
  // console. Off by default to keep production sessions quiet.
  debugLogging: false,
  boards: [],
  cards: {},
  labels: [],
  nextcloud: { ...DEFAULT_NEXTCLOUD },
};

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function uid(prefix) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function textLine(value) {
  return String(value || "").replace(/\r?\n/g, " ").trim();
}

/**
 * Accepts only the storage format used in card frontmatter: YYYY-MM-DD.
 */
function cleanDate(value) {
  const date = textLine(value);
  return /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : "";
}

function cleanColor(value) {
  const color = textLine(value).replace(/^["']|["']$/g, "");
  return /^#[0-9a-f]{6}$/i.test(color) ? color : "";
}

function dateFromISO(value) {
  const date = cleanDate(value);
  if (!date) return null;

  const [year, month, day] = date.split("-").map(Number);
  return new Date(year, month - 1, day);
}

function isoFromDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function addMonths(date, amount) {
  return new Date(date.getFullYear(), date.getMonth() + amount, 1);
}

function shortDateLabel(value) {
  const date = dateFromISO(value);
  if (!date) return "";

  return new Intl.DateTimeFormat(undefined, { day: "numeric", month: "short" })
    .format(date)
    .replace(/\.$/, "");
}

function fieldDateLabel(value) {
  const date = dateFromISO(value);
  if (!date) return "D.M.YYYY";

  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  return `${day}.${month}.${date.getFullYear()}`;
}

function dateRangeLabel(startDate, dueDate) {
  const start = cleanDate(startDate);
  const due = cleanDate(dueDate);
  if (start && due && start !== due) return `${shortDateLabel(start)} - ${shortDateLabel(due)}`;
  return shortDateLabel(due || start);
}

function parseBoolean(value) {
  const normalized = textLine(value).toLowerCase();
  return ["true", "yes", "1", "x", "done"].includes(normalized);
}

function labelKey(label) {
  return textLine(typeof label === "string" ? label : label && label.name).toLowerCase();
}

function cleanLabelName(label) {
  const name = textLine(typeof label === "string" ? label : label && label.name);
  if (name === "---" || /^(kanban-card-id|kanban-board-id|kanban-list-id|completed|start|due):/i.test(name)) return "";
  return name;
}

/**
 * Builds a readable vault-safe card filename from a title.
 */
function cardFileBaseName(value) {
  const name = textLine(value || "Card")
    .replace(/[\\/:*?"<>|#^[\]]/g, " ")
    .replace(/\s+/g, " ")
    .replace(/^\.+|\.+$/g, "")
    .trim()
    .slice(0, 80);

  return name || "Card";
}

function tagPart(value) {
  return textLine(value || "item")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "item";
}

function taskDeckListTag(boardName, listTitle) {
  return `task-deck/${tagPart(boardName)}/${tagPart(listTitle)}`;
}

function imageTarget(raw) {
  return String(raw || "")
    .trim()
    .replace(/^<|>$/g, "")
    .split("|")[0]
    .split("#")[0]
    .split("?")[0]
    .trim();
}

function isImagePath(value) {
  const match = imageTarget(value).toLowerCase().match(/\.([a-z0-9]+)$/);
  return !!(match && IMAGE_EXTENSIONS.includes(match[1]));
}

function imageRefsFromMarkdown(markdown) {
  const text = String(markdown || "");
  const refs = [];
  let match;

  const wikiRe = /!\[\[([^\]]+)\]\]/g;
  while ((match = wikiRe.exec(text))) {
    const target = imageTarget(match[1]);
    if (isImagePath(target)) refs.push({ target, markup: match[0] });
  }

  const mdRe = /!\[[^\]]*]\(([^)]+)\)/g;
  while ((match = mdRe.exec(text))) {
    const target = imageTarget(match[1]);
    if (isImagePath(target) || /^https?:\/\//i.test(target)) refs.push({ target, markup: match[0] });
  }

  return refs;
}

function stripImageEmbeds(markdown) {
  let text = String(markdown || "");
  imageRefsFromMarkdown(text).forEach((ref) => {
    text = text.replace(ref.markup, "");
  });
  return text.replace(/\n{3,}/g, "\n\n").trim();
}

function createElement(tag, className, text) {
  const element = document.createElement(tag);
  if (className) element.className = className;
  if (text !== undefined) element.textContent = text;
  return element;
}

function hasDragType(event, type) {
  const types = event.dataTransfer && event.dataTransfer.types;
  return !!types && (Array.from(types).includes(type) || (types.contains && types.contains(type)));
}

const ICON_ALIASES = {
  ellipsis: ["more-horizontal", "ellipsis"],
  "check-square": ["square-check", "check-square"],
  "plus-square": ["square-plus", "plus-square"],
  "layout-dashboard": ["layout-dashboard", "panel-top", "grid-2x2"],
  "calendar-days": ["calendar-days", "calendar"],
  pencil: ["pencil", "edit-3", "edit"],
  trash: ["trash", "trash-2"],
};

const SVG_NS = "http://www.w3.org/2000/svg";
const ICON_FALLBACKS = {
  "arrow-left": { paths: ["M19 12H5", "M12 19l-7-7 7-7"] },
  "chevron-left": { paths: ["M15 18l-6-6 6-6"] },
  "chevron-right": { paths: ["M9 18l6-6-6-6"] },
  "chevrons-left": { paths: ["M11 17l-5-5 5-5", "M18 17l-5-5 5-5"] },
  "chevrons-right": { paths: ["M6 17l5-5-5-5", "M13 17l5-5-5-5"] },
  circle: { circles: [{ cx: 12, cy: 12, r: 9 }] },
  check: { paths: ["M20 6L9 17l-5-5"] },
  "check-square": { rects: [{ x: 3, y: 3, width: 18, height: 18, rx: 3 }], paths: ["M8 12l3 3 5-6"] },
  "square-check": { rects: [{ x: 3, y: 3, width: 18, height: 18, rx: 3 }], paths: ["M8 12l3 3 5-6"] },
  "calendar-days": { rects: [{ x: 3, y: 4, width: 18, height: 17, rx: 2 }], paths: ["M8 2v4", "M16 2v4", "M3 10h18", "M8 14h.01", "M12 14h.01", "M16 14h.01", "M8 18h.01", "M12 18h.01"] },
  clock: { circles: [{ cx: 12, cy: 12, r: 9 }], paths: ["M12 7v5l3 2"] },
  bold: { paths: ["M7 5h6a4 4 0 0 1 0 8H7Z", "M7 13h7a4 4 0 0 1 0 8H7Z"] },
  italic: { paths: ["M19 4h-9", "M14 20H5", "M15 4 9 20"] },
  ellipsis: { circles: [{ cx: 6, cy: 12, r: 1.4, fill: "currentColor", stroke: "none" }, { cx: 12, cy: 12, r: 1.4, fill: "currentColor", stroke: "none" }, { cx: 18, cy: 12, r: 1.4, fill: "currentColor", stroke: "none" }] },
  "more-horizontal": { circles: [{ cx: 6, cy: 12, r: 1.4, fill: "currentColor", stroke: "none" }, { cx: 12, cy: 12, r: 1.4, fill: "currentColor", stroke: "none" }, { cx: 18, cy: 12, r: 1.4, fill: "currentColor", stroke: "none" }] },
  "grip-vertical": {
    circles: [
      { cx: 9, cy: 5, r: 1.2, fill: "currentColor", stroke: "none" }, { cx: 15, cy: 5, r: 1.2, fill: "currentColor", stroke: "none" },
      { cx: 9, cy: 12, r: 1.2, fill: "currentColor", stroke: "none" }, { cx: 15, cy: 12, r: 1.2, fill: "currentColor", stroke: "none" },
      { cx: 9, cy: 19, r: 1.2, fill: "currentColor", stroke: "none" }, { cx: 15, cy: 19, r: 1.2, fill: "currentColor", stroke: "none" },
    ],
  },
  heart: { paths: ["M20.8 8.6c0 5.3-8.8 10.4-8.8 10.4S3.2 13.9 3.2 8.6A4.5 4.5 0 0 1 12 7a4.5 4.5 0 0 1 8.8 1.6Z"] },
  info: { circles: [{ cx: 12, cy: 12, r: 9 }], paths: ["M12 10v6", "M12 7h.01"] },
  "layout-dashboard": {
    rects: [
      { x: 4, y: 4, width: 6, height: 6, rx: 1 },
      { x: 14, y: 4, width: 6, height: 6, rx: 1 },
      { x: 4, y: 14, width: 6, height: 6, rx: 1 },
      { x: 14, y: 14, width: 6, height: 6, rx: 1 },
    ],
  },
  list: { paths: ["M8 6h13", "M8 12h13", "M8 18h13", "M3 6h.01", "M3 12h.01", "M3 18h.01"] },
  link: { paths: ["M10 13a5 5 0 0 0 7.1 0l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1", "M14 11a5 5 0 0 0-7.1 0l-2 2A5 5 0 0 0 12 20.1l1.1-1.1"] },
  image: { rects: [{ x: 3, y: 5, width: 18, height: 14, rx: 2 }], circles: [{ cx: 8.5, cy: 10, r: 1.5 }], paths: ["M21 15l-5-5L5 19"] },
  paperclip: { paths: ["M21.4 11.6 12 21a6 6 0 0 1-8.5-8.5l9.9-9.9a4 4 0 1 1 5.7 5.7l-10 10a2 2 0 1 1-2.8-2.8l9.4-9.4"] },
  "help-circle": { circles: [{ cx: 12, cy: 12, r: 9 }], paths: ["M9.1 9a3 3 0 1 1 5.8 1c-.9 1.2-2.4 1.5-2.8 3", "M12 17h.01"] },
  type: { paths: ["M4 7V4h16v3", "M9 20h6", "M12 4v16"] },
  "file-text": { paths: ["M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9Z", "M14 3v6h6", "M8 13h8", "M8 17h5"] },
  "refresh-cw": { paths: ["M21 12a9 9 0 0 1-15 6.7", "M3 12A9 9 0 0 1 18 5.3", "M18 3v5h-5", "M6 21v-5h5"] },
  settings: { circles: [{ cx: 12, cy: 12, r: 3 }], paths: ["M12 2v3", "M12 19v3", "M4.9 4.9 7 7", "M17 17l2.1 2.1", "M2 12h3", "M19 12h3", "M4.9 19.1 7 17", "M17 7l2.1-2.1"] },
  pencil: { paths: ["M12 20h9", "M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z"] },
  plus: { paths: ["M12 5v14", "M5 12h14"] },
  "plus-square": { rects: [{ x: 3, y: 3, width: 18, height: 18, rx: 3 }], paths: ["M12 8v8", "M8 12h8"] },
  "square-plus": { rects: [{ x: 3, y: 3, width: 18, height: 18, rx: 3 }], paths: ["M12 8v8", "M8 12h8"] },
  trash: { paths: ["M3 6h18", "M8 6V4h8v2", "M6 6l1 15h10l1-15", "M10 11v6", "M14 11v6"] },
  x: { paths: ["M18 6 6 18", "M6 6l12 12"] },
};

function appendSvgChild(svg, tag, attrs) {
  const child = document.createElementNS(SVG_NS, tag);
  Object.entries(attrs).forEach(([key, value]) => child.setAttribute(key, String(value)));
  svg.appendChild(child);
}

function setSvgIconFallback(element, icon) {
  const fallback = ICON_FALLBACKS[icon] || ICON_FALLBACKS.plus;
  const svg = document.createElementNS(SVG_NS, "svg");
  svg.setAttribute("xmlns", SVG_NS);
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", "currentColor");
  svg.setAttribute("stroke-width", "2.2");
  svg.setAttribute("stroke-linecap", "round");
  svg.setAttribute("stroke-linejoin", "round");
  svg.setAttribute("aria-hidden", "true");

  (fallback.paths || []).forEach((d) => appendSvgChild(svg, "path", { d }));
  (fallback.circles || []).forEach((attrs) => appendSvgChild(svg, "circle", attrs));
  (fallback.rects || []).forEach((attrs) => appendSvgChild(svg, "rect", attrs));
  element.replaceChildren(svg);
}

function setIconWithFallback(element, icon, label) {
  const names = ICON_ALIASES[icon] || [icon];
  for (const name of names) {
    element.replaceChildren();
    try {
      setIcon(element, name);
      if (element.querySelector("svg")) return;
    } catch (error) {
      // Try the next compatible Lucide/Obsidian icon name.
    }
  }
  element.setAttribute("aria-label", label || icon);
  setSvgIconFallback(element, icon);
}

function iconButton(icon, label, onClick) {
  const button = createElement("button", "ot-icon-button");
  button.type = "button";
  button.title = label;
  button.setAttribute("aria-label", label);
  setIconWithFallback(button, icon, label);
  button.addEventListener("click", onClick);
  return button;
}

function textButton(icon, label, onClick, className = "") {
  const button = createElement("button", `ot-text-button ${className}`.trim());
  button.type = "button";

  const iconSlot = createElement("span", "ot-button-icon");
  setIconWithFallback(iconSlot, icon, label);

  button.append(iconSlot, createElement("span", "", label));
  button.addEventListener("click", onClick);
  return button;
}

function addButtonIcon(button, icon, label) {
  const iconSlot = createElement("span", "ot-button-icon");
  setIconWithFallback(iconSlot, icon, label || button.textContent);
  button.prepend(iconSlot);
  button.classList.add("ot-button-with-icon");
  return button;
}

/**
 * Reads a second-level Markdown section body, stopping before the next H2.
 */
// The real section headings in a card note. A "## ..." line only ends a section
// when it's one of these AND outside a fenced code block — so a user can write a
// "## " heading (or a "## " comment inside a ``` block) in Details without the
// text after it being silently truncated.
const CARD_SECTION_HEADINGS = ["Details", "Detaylar", "Checklist", "Yapılacaklar", "Kontrol listesi"];

function getSection(markdown, heading, boundaries) {
  const marker = `## ${heading}`;
  const start = String(markdown || "").indexOf(marker);
  if (start === -1) return "";

  const body = String(markdown).slice(start + marker.length);
  const boundarySet = Array.isArray(boundaries) && boundaries.length
    ? new Set(boundaries.map((h) => `## ${h}`))
    : null;

  const kept = [];
  let inFence = false;
  for (const line of body.split("\n")) {
    if (/^\s*(```|~~~)/.test(line)) { // opening/closing code fence
      inFence = !inFence;
      kept.push(line);
      continue;
    }
    if (!inFence) {
      const isBoundary = boundarySet
        ? boundarySet.has(line.trim())
        : /^##\s/.test(line.trimStart());
      if (isBoundary) break;
    }
    kept.push(line);
  }
  return kept.join("\n").trim();
}

function getSectionAny(markdown, headings) {
  for (const heading of headings) {
    const section = getSection(markdown, heading, CARD_SECTION_HEADINGS);
    if (section) return section;
  }
  return "";
}

/**
 * Converts Markdown checklist lines into the card checklist model.
 *
 * Non-checkbox lines are kept as unchecked items so notes written by hand do
 * not silently lose useful text.
 */
function parseChecklist(text) {
  return String(text || "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      // Pull off the trailing "<!--@email|name|color-->" member assignment, if any.
      let assignee = null;
      let core = line;
      const am = line.match(/\s*<!--@(.*?)-->\s*$/);
      if (am) {
        core = line.slice(0, am.index).trim();
        const parts = String(am[1] || "").split("|");
        const email = (parts[0] || "").trim();
        if (email) assignee = { email, name: (parts[1] || "").trim(), color: (parts[2] || "").trim() };
      }

      const match = core.match(/^(?:-\s*)?\[([ xX])\]\s*(.*)$/);
      if (!match) {
        return { done: false, text: core.replace(/^- /, "").trim(), assignee };
      }

      return {
        done: match[1].toLowerCase() === "x",
        text: match[2].trim(),
        assignee,
      };
    })
    .filter((item) => item.text);
}

function checklistToText(items) {
  return (items || [])
    .map((item) => `[${item.done ? "x" : " "}] ${item.text}`)
    .join("\n");
}

function checklistToMarkdown(items) {
  return (items || [])
    .map((item) => {
      const base = `- [${item.done ? "x" : " "}] ${textLine(item.text)}`;
      const a = item.assignee;
      if (a && a.email) {
        // Per-item member assignment, hidden in an HTML comment so it round-trips
        // and stays invisible in Markdown preview.
        const safe = (v) => String(v || "").replace(/[|>]/g, " ").trim();
        return `${base} <!--@${safe(a.email)}|${safe(a.name)}|${safe(a.color)}-->`;
      }
      return base;
    })
    .join("\n");
}

function checklistStats(items) {
  const total = (items || []).length;
  const done = (items || []).filter((item) => item.done).length;
  return {
    done,
    total,
    percent: total ? Math.round((done / total) * 100) : 0,
  };
}

/**
 * Reads the compact label frontmatter format: "Name|#color, Name 2|#color".
 */
function parseLabels(raw) {
  return String(raw || "")
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [name, color] = part.split("|").map((item) => item.trim());
      return { name, color: color || "#d43c35" };
    })
    .filter((label) => label.name);
}

/**
 * Writes labels back to the same compact frontmatter format parseLabels reads.
 */
function labelsToFrontmatter(labels) {
  return (labels || [])
    .map((label) => `${textLine(label.name)}|${textLine(label.color || "#d43c35")}`)
    .join(", ");
}

/**
 * Card assignees serialize to "email|Name|#color, email2|Name2|#color2".
 * Assignee UI is disabled in MVP (single-user Nextcloud sync); this serializer
 * exists so any pre-existing card frontmatter round-trips cleanly and can be
 * re-surfaced when team assignees are added back via Deck ACL.
 */
function parseAssignees(raw) {
  return String(raw || "")
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [email, name, color] = part.split("|").map((item) => (item || "").trim());
      if (!email) return null;
      return { email, name: name || email, color: color || "#8b5cf6" };
    })
    .filter(Boolean);
}

function assigneesToFrontmatter(assignees) {
  return (assignees || [])
    .filter((a) => a && a.email)
    .map((a) => `${textLine(a.email)}|${textLine(a.name || a.email).replace(/[|,]/g, " ")}|${textLine(a.color || "#8b5cf6")}`)
    .join(", ");
}

/** Two-letter uppercase initials for an avatar fallback (no picture). */
function initials(nameOrEmail) {
  const source = String(nameOrEmail || "").trim();
  if (!source) return "?";
  const namePart = source.includes("@") ? source.split("@")[0] : source;
  const words = namePart.split(/[\s._-]+/).filter(Boolean);
  if (words.length >= 2) return (words[0][0] + words[1][0]).toUpperCase();
  return namePart.slice(0, 2).toUpperCase();
}

function frontmatterValue(markdown, key) {
  const match = markdown.match(new RegExp(`^${key}:[ \\t]*(.*)$`, "m"));
  return match ? textLine(match[1]) : null;
}

// The list structure (id/title/color/order) is embedded in the board index file
// as a base64 JSON blob inside an HTML comment, so it syncs across devices and
// survives Markdown/YAML quirks (titles can be any UTF-8 text).
const LIST_META_RE = /<!--task-deck-lists:([A-Za-z0-9+/=]*)-->/;

function encodeListMeta(lists, deleted) {
  const data = {
    l: (Array.isArray(lists) ? lists : []).map((l) => ({
      i: l.id,
      t: l.title == null ? "" : String(l.title),
      c: l.color || "",
    })),
    // Sorted so an identical tombstone SET encodes to identical bytes on every
    // device — otherwise two devices that deleted lists in a different order
    // would produce different index content and churn forever.
    d: (Array.isArray(deleted) ? deleted.filter(Boolean) : []).slice().sort(),
  };
  try {
    return btoa(unescape(encodeURIComponent(JSON.stringify(data))));
  } catch (error) {
    return "";
  }
}

// Returns { lists: [{i,t,c}], deleted: [ids] } or null. Tolerates the older
// bare-array form ([{i,t,c}]) as { lists, deleted: [] }.
function decodeListMeta(markdown) {
  const match = String(markdown || "").match(LIST_META_RE);
  if (!match || !match[1]) return null;
  try {
    const obj = JSON.parse(decodeURIComponent(escape(atob(match[1]))));
    if (Array.isArray(obj)) return { lists: obj, deleted: [] };
    if (obj && typeof obj === "object") {
      return { lists: Array.isArray(obj.l) ? obj.l : [], deleted: Array.isArray(obj.d) ? obj.d : [] };
    }
    return null;
  } catch (error) {
    return null;
  }
}

/**
 * Parses a Task Deck card note into the in-memory card fields.
 *
 * The parser is intentionally forgiving because users may edit these files by
 * hand. Missing frontmatter fields return empty strings or nulls so callers can
 * keep existing saved values when appropriate.
 */
function parseCardMarkdown(markdown) {
  const titleMatch = markdown.match(/^#\s+(.+)$/m);
  const labels = frontmatterValue(markdown, "labels");
  const assignees = frontmatterValue(markdown, "assignees");
  const completed = frontmatterValue(markdown, "completed");
  const start = frontmatterValue(markdown, "start");
  const due = frontmatterValue(markdown, "due");
  const positionRaw = frontmatterValue(markdown, "position");
  const position = positionRaw !== null && positionRaw !== "" && !Number.isNaN(Number(positionRaw)) ? Number(positionRaw) : null;

  return {
    id: frontmatterValue(markdown, "kanban-card-id") || "",
    boardId: frontmatterValue(markdown, "kanban-board-id") || "",
    listId: frontmatterValue(markdown, "kanban-list-id") || "",
    listTitle: frontmatterValue(markdown, "task-deck-list") || "",
    position,
    title: titleMatch ? titleMatch[1].trim() : "",
    labels: labels !== null ? parseLabels(labels) : [],
    assignees: assignees !== null ? parseAssignees(assignees) : null,
    completed: completed !== null ? parseBoolean(completed) : null,
    startDate: start !== null ? cleanDate(start) : null,
    dueDate: due !== null ? cleanDate(due) : null,
    details: getSectionAny(markdown, ["Details", "Detaylar"]),
    checklist: parseChecklist(getSectionAny(markdown, ["Checklist", "Yapılacaklar", "Kontrol listesi"])),
  };
}

module.exports = {
  VIEW_TYPE,
  LEGACY_CARD_FOLDER,
  LEGACY_BOARD_INDEX_SUFFIX,
  BOARD_INDEX_MARKER,
  TASK_DECK_ICON,
  TASK_DECK_ICON_SVG,
  LIST_DRAG_TYPE,
  IMAGE_EXTENSIONS,
  DEFAULT_LABEL_COLOR,
  LABEL_COLORS,
  LIST_COLORS,
  DEFAULT_DATA,
  DEFAULT_NEXTCLOUD,
  clone,
  uid,
  textLine,
  cleanDate,
  cleanColor,
  dateFromISO,
  isoFromDate,
  addMonths,
  shortDateLabel,
  fieldDateLabel,
  dateRangeLabel,
  parseBoolean,
  labelKey,
  cleanLabelName,
  cardFileBaseName,
  taskDeckListTag,
  imageTarget,
  isImagePath,
  imageRefsFromMarkdown,
  stripImageEmbeds,
  createElement,
  hasDragType,
  iconButton,
  textButton,
  addButtonIcon,
  getSection,
  getSectionAny,
  parseChecklist,
  checklistToText,
  checklistToMarkdown,
  checklistStats,
  parseLabels,
  labelsToFrontmatter,
  parseAssignees,
  assigneesToFrontmatter,
  initials,
  parseCardMarkdown,
  encodeListMeta,
  decodeListMeta,
};
